source 'https://rubygems.org'

ruby ENV['RUBY_VERSION'] || '2.0.0'

gem 'rake'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'activesupport'
gem 'gql'
gem 'dotenv'

group :development do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end

