$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)

require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require 'app'

    # needed for loading fixtures
    include App::Models

    # hook sinatra-activerecord registration
    App::Client
  end

  namespace :data do
    desc "Reset all data in the db to fixtures state"
    task :reset => :load_config do
      [Album, Attribution, Band, Membership, MembershipRole, Person, Role, Song].map(&:delete_all)
      Rake::Task['db:fixtures:load'].invoke
    end
  end
end
